### ISSUE TITLE
Не всегда UNIX-сокет закрывается правильно

### ISSUE THREAD

**Issue by Ponywka** [Ponywka/kvas2-go#3]
```
1:57AM ERR error while listening unix socket error="accept unix /opt/var/run/kvas2-go.sock: use of closed network connection"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20074c]
goroutine 102 [running]:
main.(*App).Listen.func6.1({0x0, 0x0})
        kvas2-go/kvas2.go:130 +0x40
created by main.(*App).Listen.func6 in goroutine 44
        kvas2-go/kvas2.go:129 +0x74
```

**Comment by Ponywka** [comment]
Исправлено в https://github.com/Ponywka/kvas2-go/commit/3e42d0deb0e209f9461b37983a120bbe950245ea
